const loveQuotes: string[] = [
  "Yêu em là điều tuyệt vời nhất đã đến trong cuộc đời anh.",
  "Anh không cần cả thế giới, anh chỉ cần em thôi.",
  "Em là nắng của ngày mưa, là mưa của ngày nắng trong lòng anh.",
  "Bên em, thời gian trôi qua mà anh chẳng hề hay biết.",
  "Nếu được chọn lại, anh vẫn sẽ chọn em.",
  "Em là câu trả lời cho mọi câu hỏi của trái tim anh.",
  "Yêu không cần nói nhiều, chỉ cần ở bên nhau là đủ.",
  "Anh yêu em từ cái nhìn đầu tiên và sẽ yêu đến cái nhìn cuối cùng.",
  "Em là giấc mơ đẹp nhất mà anh không muốn tỉnh dậy.",
  "Hạnh phúc là khi có em trong vòng tay.",
  "Mỗi ngày bên em là một ngày đáng sống.",
  "Em là lý do anh mỉm cười mỗi sáng thức dậy.",
  "Tình yêu của chúng mình như rượu vang, càng lâu càng đậm đà.",
  "Anh không hoàn hảo, nhưng anh hoàn hảo dành cho em.",
  "Em khiến anh muốn trở thành người tốt hơn mỗi ngày.",
  "Nơi nào có em, nơi đó là nhà của anh.",
  "Yêu em, anh chẳng cần lý do.",
  "Em là bản tình ca đẹp nhất đời anh.",
  "Cả thế giới có thể thay đổi, nhưng tình anh dành cho em thì không.",
  "Anh sẽ yêu em cho đến khi trái tim ngừng đập.",
  "Em là ánh sáng dẫn lối anh qua những ngày tăm tối.",
  "Được yêu em là điều may mắn nhất đời anh.",
  "Tình yêu không đếm ngày tháng, nhưng ngày tháng chứng minh tình yêu.",
  "Em là miếng ghép cuối cùng làm trọn vẹn cuộc đời anh.",
  "Yêu là khi anh nhìn em và thấy cả tương lai phía trước.",
  "Trái tim anh đã tìm được bến đỗ khi gặp em.",
  "Em là điều bất ngờ đẹp nhất cuộc đời anh.",
  "Mỗi khoảnh khắc bên em đều là kho báu quý giá.",
  "Anh yêu em hơn cả những gì lời nói có thể diễn tả.",
  "Em là ngôi sao sáng nhất trên bầu trời đêm của anh.",
  "Tình yêu là khi xa em một phút cũng thấy nhớ.",
  "Em đã biến cuộc sống bình thường thành cuộc phiêu lưu tuyệt vời.",
  "Anh không tin vào cổ tích, cho đến khi gặp em.",
  "Yêu em, anh học được thế nào là hạnh phúc thật sự.",
  "Em là hơi thở, là nhịp tim, là tất cả của anh.",
  "Có em, mọi khó khăn đều trở nên nhẹ nhàng hơn.",
  "Anh muốn cùng em đi đến cuối con đường.",
  "Em là ly cà phê ngọt ngào mỗi buổi sáng.",
  "Tình yêu của anh dành cho em không có ngày hết hạn.",
  "Bên em, anh thấy mình là người giàu có nhất thế gian.",
  "Em là mùa xuân vĩnh cửu trong trái tim anh.",
  "Yêu em nhiều hơn hôm qua, nhưng ít hơn ngày mai.",
  "Em là người anh muốn gọi tên đầu tiên khi thức dậy.",
  "Hãy để anh là bờ vai cho em tựa vào mỗi khi mệt mỏi.",
  "Tình yêu không cần hoàn hảo, chỉ cần chân thành.",
  "Em là phép màu mà anh đã chờ đợi cả đời.",
  "Anh yêu cả những điều nhỏ nhất ở em.",
  "Cuộc đời ngắn ngủi, nhưng tình yêu của mình thì mãi mãi.",
  "Em là nốt nhạc ngọt ngào trong bản giao hưởng cuộc đời anh.",
  "Yêu em, anh thấy thế giới này đẹp hơn rất nhiều.",
  "Em là điều duy nhất anh không bao giờ muốn mất.",
  "Cảm ơn em đã đến bên anh và ở lại.",
  "Tình yêu là khi nhìn em cười mà quên hết ưu phiền.",
  "Anh sẽ giữ tay em thật chặt, dù bão giông hay nắng đẹp.",
  "Em là vị ngọt của cuộc đời, là hương thơm của tình yêu.",
  "Không ai hiểu anh bằng em, và không ai yêu em bằng anh.",
  "Em là ngày nắng đẹp sau cơn mưa dài.",
  "Yêu em là thói quen đẹp nhất mà anh không muốn bỏ.",
  "Mỗi nhịp tim đều gọi tên em.",
  "Em là cầu vồng sau những cơn mưa trong đời anh.",
];

export default loveQuotes;
